name: tech_ecommerce_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.5.3+2
  device_preview: ^1.1.0
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.4

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - images/sally_images/

